# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89691536906b8d2c25cc554ea846db832795dd2eefbb2f16792887ca3d5991d286a6b876d4cc5c02f98804e6e001e918007de1af9f417cb467f2f4c928c46c4f

test:
  secret_key_base: f45369c3836dd9b4451595c1f2f54af2030dd17b0e3759114889e27ae892d65d180751b8c9a4d860f368d5651e2c80f24b9e933c951053c952b567088a84cd79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
